language: php

before_install:
  - wget https://scrutinizer-ci.com/ocular.phar
 
script:
  - sudo chown $USER /opt
  - ant composer-init
  - ant -Dprepare.distribution.build=false build
  - php ocular.phar code-coverage:upload --format=php-clover $TRAVIS_BUILD_DIR/target/reports/unit/clover.xml

notifications:
  email: tw@techdivision.com
  hipchat: 95d47a72c5372d4a0fef20048c3200@Appserver