
env:
  global:
    - BUILD_NUMBER=${TRAVIS_BUILD_NUMBER}

matrix:
  include:
    - os: osx
      osx_image: xcode6.4
      before_install:
        - brew update
        - brew install ant
      script:
        - sudo chown $USER /opt
        - ant dependencies-init
        - ant local-build -Dos.family=mac
    - os: linux
      dist: xenial
      before_install:
        - sudo apt-get update
        - sudo apt-get install ant
      script:
        - sudo chown $USER /opt
        - sudo ant dependencies-init
        - sudo ant local-build

deploy:
  provider: releases
  api_key: 36d3eff742ce62780ec97fdf823340f5dc95ce4f
  file_glob: true
  file: "build/*"
  skip_cleanup: true
  on:
    tags: true
    branch: '1.1'
    repo: wick-ed/runtime

notifications:
  email: tw@techdivision.com
  hipchat: 95d47a72c5372d4a0fef20048c3200@Appserver
