
env:
  global:
    - BUILD_NUMBER=${TRAVIS_BUILD_NUMBER}

matrix:
  include:
    - os: osx
      osx_image: xcode6.4
      before_install:
        - brew update
        - brew install ant
      script:
        - sudo chown $USER /opt
        - ant dependencies-init
        - ant local-build -Dos.family=mac
    - os: linux
      dist: xenial
      services:
        - docker
      script:
        - docker run --rm -v `pwd`:/build -w /build -e TRAVIS_TAG debian:9 bash -c "apt-get update; apt-get install -y ant git; ant dependencies-init; ant local-build -Dbuild.number=$BUILD_NUMBER -Dtarget-os.major.version=9 -Dtarget-os.minor.version=9"

deploy:
  provider: releases
  api_key:
    secure: "qb7Xvv1hm0AK8g+WX8O/E/thc0ul5xFLJ5XlB1gpzS82Dohc3+rgKK0/Jl1hext2/Y7xSaBfjvpP4dgULS1F+PZPhwNQPTJdpxDy7mKcCWkZ4Gf5/Quncn23TFa8uR/WtyIoynQHHkb2QiIYoNn4Ovc+ySEVgQYEAX8dCxrPEOk="
  file_glob: true
  file: "build/*"
  skip_cleanup: true
  on:
    tags: true
    branch: '1.1'
    repo: appserver-io-php/runtime

notifications:
  email: tw@techdivision.com
