os: osx

osx_image: xcode6.4

env:
  - BUILD_NUMBER = $TRAVIS_BUILD_NUMBER

before_install:
  - brew update
  - brew install ant

script:
  - sudo chown $USER /opt
  - ant dependencies-init
  - ant local-build -Dos.family=mac
  
deploy:
  provider: releases
  api_key:
    secure: lgqc8VZI7GcenyFh3udW67a9FGXfR4GUoaOV77nl17JB3+8CMpXmFozCECaXZFe6Bek9kr7wzIy68LJvR/GoIoFMmEiHRAzuE8+0eg7gpN0D+N/IlEUWU7AyKdL+7Ad1GrpQuulJIJNPgBkzcbVhKQnq5kFYog+SEFyl4s0aVF4=
  file_glob: true
  file: "build/*"
  skip_cleanup: true
  on:
    tags: true
    branch: '1.1'
    repo: appserver-io-php/runtime

notifications:
  email: tw@techdivision.com
  hipchat: 95d47a72c5372d4a0fef20048c3200@Appserver
