language: objective-c

php:
  - 5.4
  - 5.5

matrix:
  allow_failures:
    - php: 5.5
 
script:
 - sudo ant -Dos.family=mac create-pkg

notifications:
  email: tw@techdivision.com
  hipchat: 95d47a72c5372d4a0fef20048c3200@Appserver