os: osx

before_install:
  - brew update
  - brew outdated ant || brew upgrade ant
 
script:
  - sudo chown $USER /opt
  - ant dependencies-init
  - ant local-build -Dos.family=mac

notifications:
  email: tw@techdivision.com
  hipchat: 95d47a72c5372d4a0fef20048c3200@Appserver