
env:
  global:
    - BUILD_NUMBER=${TRAVIS_BUILD_NUMBER}

matrix:
  include:
    - os: osx
      osx_image: xcode6.4
      before_install:
        - brew update
        - brew install ant
      script:
        - sudo chown $USER /opt
        - ant dependencies-init
        - ant local-build -Dos.family=mac
    - os: linux
      dist: xenial
      services:
        - docker
      before_install:
        - sudo apt-get update
        - sudo apt-get install ant
      script:
        - docker run --rm -v `pwd`:/build -w /build debian:9 bash -c "apt-get update; apt-get install -y ant; ant dependencies-init; ant local-build"

deploy:
  provider: releases
  api_key:
    secure: "T/+tptqFVgBCPgVPQqEL7ciWg5N4hp4bWdq9jG7AIB3K1inu1LL4HzggOfyeSktUOW63SZdEoWqrXaYk0d4+4f811Dzign3Eqi/m/yw2Opwh0jbpOTvaQBZfN8/xBAB9/TfsPyFWq4buF8fI5Njew7wbxs/n1c701L2zFtzmxEM="
  file_glob: true
  file: "build/*"
  skip_cleanup: true
  on:
    tags: true
    branch: '1.1'
    repo: wick-ed/runtime
