
env:
  global:
    - BUILD_NUMBER=${TRAVIS_BUILD_NUMBER}

matrix:
  include:
    - os: osx
      osx_image: xcode6.4
      before_install:
        - brew update
        - brew install ant
      script:
        - sudo chown $USER /opt
        - ant dependencies-init
        - ant local-build -Dos.family=mac
    - os: linux
      dist: xenial
      services:
        - docker
      script:
        - docker run --rm -v `pwd`:/build -w /build -e TRAVIS_TAG debian:9 bash -c "apt-get update; apt-get install -y ant git; ant dependencies-init; ant local-build -Dbuild.number=$BUILD_NUMBER -Dtarget-os.major.version=9 -Dtarget-os.minor.version=9"

deploy:
  provider: releases
  api_key:
    secure: "fDjFJMc3Rt312Da6LpBgH4SK7JhCppgRJZYiqHu1zkjLlCUi10rougJuA3BL+c531Udb0Ko1bjGrcRZVHmg1Grtn8lDwKAfSGC8x7Dc1gC788gA9hAHVIJ95WVgUOfALWFQ1e3re9cUhlCrRz0Pc6ZxgOaI9Krg9TwaisuXu/Lg="
  file_glob: true
  file: "build/*"
  skip_cleanup: true
  on:
    tags: true
    branch: '1.1'
    repo: appserver-io-php/runtime

notifications:
  email: tw@techdivision.com
