language: objective-c

php:
  - 5.4
  - 5.5
 
script:
  - sudo ant composer-init
  - sudo ant build
  - php ocular.phar code-coverage:upload --format=php-clover $TRAVIS_BUILD_DIR/target/reports/unit/clover.xml

notifications:
  email: tw@techdivision.com
  hipchat: 95d47a72c5372d4a0fef20048c3200@Appserver