
env:
  global:
    - BUILD_NUMBER=${TRAVIS_BUILD_NUMBER}

matrix:
  include:
    - os: osx
      osx_image: xcode6.4
      before_install:
        - brew update
        - brew install ant
      script:
        - sudo chown $USER /opt
        - ant dependencies-init
        - ant local-build -Dos.family=mac
    - os: linux
      dist: xenial
      services:
        - docker
      script:
        - docker run --rm -v `pwd`:/build -w /build debian:9 -e "TRAVIS_TAG=$TRAVIS_TAG" bash -c "apt-get update; apt-get install -y ant git; ant dependencies-init; ant local-build -Dbuild.number=$BUILD_NUMBER -Dtarget-os.major.version=9 -Dtarget-os.minor.version=9"

deploy:
  provider: releases
  api_key:
    secure: lgqc8VZI7GcenyFh3udW67a9FGXfR4GUoaOV77nl17JB3+8CMpXmFozCECaXZFe6Bek9kr7wzIy68LJvR/GoIoFMmEiHRAzuE8+0eg7gpN0D+N/IlEUWU7AyKdL+7Ad1GrpQuulJIJNPgBkzcbVhKQnq5kFYog+SEFyl4s0aVF4=
  file_glob: true
  file: "build/*"
  skip_cleanup: true
  on:
    tags: true
    branch: '1.1'
    repo: appserver-io-php/runtime

notifications:
  email: tw@techdivision.com
