#!/bin/sh

# Create composer symlink
ln -s /opt/appserver/bin/composer.phar /opt/appserver/bin/composer

# Set needed files as accessable for the configured user
chown -R ${appserver.user}:${appserver.group} /opt/appserver/var
chown -R ${appserver.user}:${appserver.group} /opt/appserver/webapps
chown -R ${appserver.user}:${appserver.group} /opt/appserver/deploy

# Set the permissions
chmod 755 /etc/init.d/appserver
chmod 755 /etc/init.d/appserver-watcher
chmod 755 /etc/init.d/appserver-php5-fpm

# Start the services
/etc/init.d/appserver start
/etc/init.d/appserver-watcher start
/etc/init.d/appserver-php5-fpm start

exit 0
