# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # Basic default configuration
  config.vm.box = "chef/${os.distribution}-${target-os.version}"
  config.vm.box_url = "https://vagrantcloud.com/chef/boxes/${os.distribution}-${target-os.version}"

  # Basic network configuration
  config.vm.host_name = "${vagrant-box.name}"

  # Shell provisioning
  config.vm.provision "shell", path: "buildfiles/${os.family}/${os.distribution}/provision.sh"

  # Share the build folder as read only
  config.vm.synced_folder "${build.dir}", "${vagrant-build.dir}"
  config.vm.synced_folder "${reports.dir}", "${vagrant-reports.dir}"
  config.vm.synced_folder "${src.dir}", "${vagrant-src.dir}"
  config.vm.synced_folder "${lib.dir}", "${vagrant-lib.dir}"

  # Extend the timeout for initial connection
  config.vm.boot_timeout = 1200

  config.vm.provider "virtualbox" do |vb|
    host = RbConfig::CONFIG['host_os']

    # Give VM 6Gb system memory & access to all cpu cores on the host
    mem = 6144
    if host =~ /darwin/
      cpus = `sysctl -n hw.ncpu`.to_i
    elsif host =~ /linux/
      cpus = `nproc`.to_i
    else # sorry Windows folks, I can't help you
      cpus = 2
    end

    vb.customize ["modifyvm", :id, "--memory", mem]
    vb.customize ["modifyvm", :id, "--cpus", cpus]
  end

  config.vm.define :"${vagrant-box.name}" do |t|
    end
end
