#!/bin/sh

# Create composer symlink
ln -s /opt/appserver/bin/composer.phar /opt/appserver/bin/composer

# Set needed files as accessable for the configured user
chown -R ${appserver.user}:${appserver.group} /opt/appserver/var
chown -R ${appserver.user}:${appserver.group} /opt/appserver/webapps
chown -R ${appserver.user}:${appserver.group} /opt/appserver/deploy

# Start the services
/opt/appserver/sbin/appserverctl start
/opt/appserver/sbin/appserver-watcherctl start
/opt/appserver/sbin/appserver-php5-fpmctl start

exit 0
